name: 02 - Manually create a shared environment

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}


on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install

      - name: Set up Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: NPM install
        working-directory: cdk
        run: npm install

      - name: Deploy network stack
        working-directory: cdk
        run: npm run network:deploy
