name: MovieBooker deployment

on:
  push:
    branches:
      - main
#
#permissions:
#  id-token: write
#  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        run: | 
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo ${GITHUB_REF#refs/heads/}
        id: get_branch

      - name: Get repository name
        run:  echo "REPOSITORY_NAME=`echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//"`" >> $GITHUB_ENV
        shell: bash

      - name: Get IAM Role and Region to login into ECR
        id: get_ecr-details
        run: |
          branch_name=${{ steps.get_branch.outputs.branch }} 
          if [[ $branch_name == 'main' || $branch_name == 'staging' || $branch_name == 'master' ]]
            then
              iamRole=${{ secrets.AWS_PROD_PLATFORM_ECR_ACCESS }}
              region='us-east-1'
            else
              iamRole=${{ secrets.AWS_DEV_PLATFORM_ECR_ACCESS }}
              region='ap-south-1'
          fi